<!DOCTYPE html>
<html>
<head>
    <title> Privacy Policy for Distribuidora Dax
    </title>
</head>
<body>
    <div style="max-width: 800px; margin: 0 auto; padding: 24px;">
    <h1>Privacy Policy for Distribuidora Dax</h1>
  <p><strong>Last updated:</strong> April 17, 2025</p>
  <p>
    This Privacy Policy describes the policies and procedures of Distribuidora Dax ("we", "us", or "our"), developed by Ernesto Arias e Ignacio Arias, on the collection, use, and disclosure of your information when you use our application and tells you about your privacy rights and how the law protects you.
  </p>
  <p>
    By using the Distribuidora Dax app, you agree to the collection and use of information in accordance with this Privacy Policy.
  </p>

  <h2>Interpretation and Definitions</h2>
  <h3>Definitions</h3>
  <ul>
    <li><strong>Application</strong> refers to Distribuidora Dax, the software program provided by Ernesto Arias e Ignacio Arias.</li>
    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Distribuidora Dax, developed by Ernesto Arias e Ignacio Arias.</li>
    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
    <li><strong>Service</strong> refers to the Application.</li>
    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
  </ul>

  <h2>Collecting and Using Your Personal Data</h2>
  <h3>Types of Data Collected</h3>
  <ul>
    <li><strong>Personal Data:</strong> While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include, but is not limited to: email address, name, phone number, address, and usage data.</li>
    <li><strong>Usage Data:</strong> Usage Data is collected automatically when using the Service and may include information such as your device's IP address, browser type, pages visited, and other diagnostic data.</li>
  </ul>

  <h3>Use of Your Personal Data</h3>
  <ul>
    <li>To provide and maintain our Service</li>
    <li>To manage Your Account</li>
    <li>For the performance of a contract</li>
    <li>To contact You</li>
    <li>To provide You with news, offers, and information</li>
    <li>To manage Your requests</li>
    <li>For business transfers</li>
    <li>For other purposes such as data analysis and service improvement</li>
  </ul>

  <h3>Sharing Your Personal Data</h3>
  <ul>
    <li>With Service Providers</li>
    <li>For business transfers</li>
    <li>With Affiliates</li>
    <li>With business partners</li>
    <li>With other users (if you share information publicly)</li>
    <li>With your consent</li>
  </ul>

  <h3>Retention and Transfer of Your Personal Data</h3>
  <p>
    We retain your Personal Data only as long as necessary and may transfer it to locations outside your jurisdiction. By using the Service, you consent to such transfers.
  </p>

  <h3>Delete Your Personal Data</h3>
  <p>
    You have the right to request deletion of your Personal Data. Contact us at 
    <a href="mailto:ernesarias13@gmail.com">ernesarias13@gmail.com</a> or 
    <a href="mailto:igna.arias@gmail.com">igna.arias@gmail.com</a> for any requests.
  </p>

  <h3>Disclosure of Your Personal Data</h3>
  <ul>
    <li>For business transactions</li>
    <li>To comply with legal obligations</li>
    <li>To protect and defend the rights or property of the Company</li>
    <li>To prevent or investigate possible wrongdoing</li>
    <li>To protect the personal safety of users or the public</li>
    <li>To protect against legal liability</li>
  </ul>

  <h3>Security of Your Personal Data</h3>
  <p>
    We strive to use commercially acceptable means to protect your Personal Data, but cannot guarantee its absolute security.
  </p>

  <h3>Children's Privacy</h3>
  <p>
    Our Service does not address anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us.
  </p>

  <h3>Links to Other Websites</h3>
  <p>
    Our Service may contain links to other websites not operated by us. We advise you to review the Privacy Policy of every site you visit.
  </p>

  <h3>Changes to this Privacy Policy</h3>
  <p>
    We may update Our Privacy Policy from time to time. Changes are effective when posted on this page.
  </p>

  <h3>Contact Us</h3>
  <p>
    If you have any questions about this Privacy Policy, you can contact us by email: 
    <a href="mailto:ernesarias13@gmail.com">ernesarias13@gmail.com</a> or 
    <a href="mailto:igna.arias@gmail.com">igna.arias@gmail.com</a>
  </p>

  <hr />
  <p style="font-size: 12px; color: #888;">
    This Privacy Policy applies to the Distribuidora Dax app, developed by Ernesto Arias e Ignacio Arias, as listed on Google Play.
  </p>
</div>
</body>
</html>
